name: GitHub Action Name
description: A GitHub Action Descriptionto Open a specified GitHub issue using the GitHub API
author: Lee Lott

inputs:
  deployment-id:
    description: 'The id of the deployment to be updated'
    required: true
  state:
    description: 'The new status of the deployment'
    required: true
  description:
    description: 'A short description of the deployment'
    required: true  
  org-name:
    description: 'The name of the GitHub Organization'
    required: true
  repo-name:
    description: 'The name of the repository'
    required: true
  token:
    description: 'GitHub token with access to create a deployment'
    required: true

outputs:
  result:
    description: 'Result of the action ("success" or "failure")'
    value: ${{ steps.action.outputs.result }}
  error-message:
    description: 'Error message if the action fails'
    value: ${{ steps.action.outputs.error-message }}
  deployment-status-id:
    description: 'The id of the deployment status'
    value: ${{ steps.action.outputs.deployment_status_id }}
  deployment-status-state: 
    description: 'The state of the deployment status'
    value: ${{ steps.action.outputs.deployment_status_state }}    

runs:
  using: composite
  steps:
    - name: Set Deployment State
      id: action
      shell: pwsh
      run: |        
        . "${{ github.action_path }}/action.ps1"
        Set-DeploymentStatus `
          -DeploymentId "${{ inputs.deployment-id }}" `
          -State "${{ inputs.state }}" `
          -Description "${{ inputs.description }}" `
          -OrgName "${{ inputs.org-name }}" `
          -RepoName "${{ inputs.repo-name }}" `
          -Token "${{ inputs.token }}"       
